import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/styles.css";
import Header from "@/components/Header/page";
import ReduxProvider from "./ReduxProvider";
import { DataProvider } from "./DataContext";
import { ThemeProvider } from "@/components/theme-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { ModeToggle } from "@/components/Dark-light/page";
import ConditionalFooter from "@/components/ConditionalFooter/page"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "amazima Restaurant",
  description: "Generated by create next app",
};
const CLIENT_ID = process.env.CLIENT_ID ?? "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        style={{ backgroundImage: `url("images/wallp.jpg")`,
                        backgroundSize: 'cover',
                        backgroundPosition: 'center' }}
      >
        <GoogleOAuthProvider clientId={CLIENT_ID}>
        <ReduxProvider>
                <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              > 
              <DataProvider>
        <Header />
        {children}
        <ModeToggle />
        <ConditionalFooter/>
        </DataProvider>
        </ThemeProvider> 
        </ReduxProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
